In [15]:
import pandas as pd
import numpy as np

In [16]:
path = r"..\data\student.csv"
df = pd.read_csv(path)

In [17]:
df.head(5)

,student_id,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
0,1,23,Female,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,2,57.21,10,57,81.87,33.78
1,2,20,Male,6.14,6.58,5.48,1.51,3.13,1.73,13,403,28,10,91.27,10,49,60.90,48.99
2,3,29,Female,4.98,3.26,4.83,3.63,0.18,4.71,1,419,102,8,63.14,2,38,86.22,36.60
3,4,27,Female,3.19,4.58,10.06,3.95,5.75,2.52,9,178,28,18,40.51,6,50,71.77,19.87
4,5,24,Male,7.67,6.21,3.02,1.59,5.46,5.65,8,436,105,7,45.53,6,41,90.13,52.90

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             20000 non-null  int64
 1   age                    20000 non-null  int64
 2   gender                 20000 non-null  object
 3   study_hours_per_day    20000 non-null  float64
 4   sleep_hours            20000 non-null  float64
 5   phone_usage_hours      20000 non-null  float64
 6   social_media_hours     20000 non-null  float64
 7   youtube_hours          20000 non-null  float64
 8   gaming_hours           20000 non-null  float64
 9   breaks_per_day         20000 non-null  int64
 10  coffee_intake_mg       20000 non-null  int64
 11  exercise_minutes       20000 non-null  int64
 12  assignments_completed  20000 non-null  int64
 13  attendance_percentage  20000 non-null  float64
 14  stress_level           20000 non-null  int64
 15  focus_score            20000 non-null  int64
 16  final_grade            20000 non-null  float64
 17  productivity_score     20000 non-null  float64
dtypes: float64(9), int64(8), object(1)
memory usage: 2.7+ MB

In [30]:
df.drop(columns=["gender", "student_id"]).describe()

,age,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score,exercise_hours
count,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,23.00745,5.254562,6.517799,6.250479,4.003655,2.990177,2.988339,7.542400,249.654550,59.648050,9.494100,69.947435,5.478750,64.444350,70.266409,50.180419,0.994134
std,3.75489,2.742876,2.029784,3.313082,2.305154,1.729815,1.732803,4.016231,143.711231,34.611751,5.801469,17.397431,2.866943,20.176114,17.282277,16.086666,0.576863
min,17.00000,0.500000,3.000000,0.500000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,40.000000,1.000000,30.000000,40.000000,0.000000,0.000000
25%,20.00000,2.900000,4.770000,3.380000,2.000000,1.487500,1.490000,4.000000,125.000000,30.000000,4.000000,54.810000,3.000000,47.000000,55.460000,38.700000,0.500000
50%,23.00000,5.250000,6.510000,6.240000,4.010000,2.980000,2.970000,8.000000,249.000000,60.000000,9.000000,69.985000,5.000000,65.000000,70.315000,50.235000,1.000000
75%,26.00000,7.640000,8.310000,9.102500,5.970000,4.480000,4.490000,11.000000,373.000000,90.000000,15.000000,85.050000,8.000000,82.000000,85.340000,61.782500,1.500000
max,29.00000,10.000000,10.000000,12.000000,8.000000,6.000000,6.000000,14.000000,499.000000,119.000000,19.000000,100.000000,10.000000,99.000000,99.990000,100.000000,1.983333

- to encode gender

In [19]:
df["exercise_minutes"].unique()

array([111,  28, 102, 105,  12, 103,  42, 107,  46,  75,  26,  48, 114,
       118,  31,  65,  71,  27,  50,  61,  85,  17, 113,  70,  33, 109,
        82, 101,  80,  55,  14,  53,  32,  64,  66,   5, 116,  20,  68,
       104,  79,  78,   9,  60,   3, 110,  13,  39,   4,  72,  83,  21,
        90, 108, 112,  40,  95,  99,  57,  29,   1,  94,  24,  52,  56,
        93,  54,  98,  69,  81,  47,  22,  19,  76, 115,  77,  44,  59,
       119,  45,  86,  73,  15,   7,   0,  89,   2,  49,  35,   6,  11,
        43,  18,  36,  97,  10,  63,  96,  41,  25,  84,  30,  92,  67,
        23,   8,  58, 100,  16, 106,  91,  38,  88,  51,  62,  87,  34,
       117,  37,  74])

`exercise_minutes` is more appropriate in the hour format to preserve more or less the same scale. That is why it will first be converted to float and then to hours.

In [20]:
df['exercise_minutes']=df["exercise_minutes"].astype("float")

In [21]:
print(df["exercise_minutes"].dtype)

float64

In [26]:
df["exercise_hours"] = df["exercise_minutes"] / 60
print(df[["exercise_minutes", "exercise_hours"]])

       exercise_minutes  exercise_hours
0                 111.0        1.850000
1                  28.0        0.466667
2                 102.0        1.700000
3                  28.0        0.466667
4                 105.0        1.750000
...                 ...             ...
19995               0.0        0.000000
19996              13.0        0.216667
19997               1.0        0.016667
19998               1.0        0.016667
19999              70.0        1.166667

[20000 rows x 2 columns]

In [23]:
df.isnull().sum()

student_id               0
age                      0
gender                   0
study_hours_per_day      0
sleep_hours              0
phone_usage_hours        0
social_media_hours       0
youtube_hours            0
gaming_hours             0
breaks_per_day           0
coffee_intake_mg         0
exercise_minutes         0
assignments_completed    0
attendance_percentage    0
stress_level             0
focus_score              0
final_grade              0
productivity_score       0
dtype: int64